#!/usr/bin/env python3

#Guess what this does.

def recurs(x):
    if x == 0:
        return 0
    print(f'x = {x} going down')
    x = recurs(x-1)
    print(f'x = {x} going up')
    return(x+2)

x = 11

x = recurs(x)
print (x)
